name: hanayama-rotor
channels:
  - defaults
  - conda-forge
dependencies:
  - graphviz=9.0.0
  - matplotlib=3.8.2
  - networkx=3.2.1
  - pip=24.0
  - pygraphviz=1.12
  - pytest=8.0.0
  - pyvis=0.3.1
  - returns=0.22.0
  - black=24.1.1
  - flake8=7.0.0
  - isort=5.13.2
  - mypy=1.8.0
  - pre-commit=3.6.0
