name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: hanayama-rotor
        environment-file: environment-dev.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Install pre-commit
      run: |
        conda init
        conda activate hanayama-rotor
        conda install -c conda-forge pre-commit

    - name: Run pre-commit hooks
      run: |
        conda init
        conda activate hanayama-rotor
        pre-commit run --all-files

    - name: Run pytest
      run: |
        conda activate hanayama-rotor
        pytest
